name: 'Setup Node'
description: 'Set up a Node.js environment and cache pnpm dependencies'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Enable Corepack and pnpm
      # Corepack is bundled with recent Node.js releases and is the recommended
      # way to make pnpm available in CI. It avoids global npm installs.
      run: |
        corepack enable
        corepack prepare pnpm@latest --activate
      shell: bash
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile
      shell: bash
