version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-backend_development}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - ./backend:/app:cached
    ports:
      - "${RAILS_PORT:-3001}:3000"
    env_file:
      - .env
    environment:
      - RAILS_PORT=${RAILS_PORT:-3001}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
